language: node_js
node_js:
- "12.13.0"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run NewmanRUN.json -e NEW_API.json -g globals.json
